# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0014_auto_20180211_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
